### ISSUE TITLE
covidcases.js (linea 12)

### ISSUE THREAD

**Issue by aaizemberg** [aatar/covid-api#1]
Les deje un comentario en la linea 12 de este archivo: https://github.com/aatar/covid-api/blob/main/app/models/covidcases.js
Yo ya saque (alter table "CovidCases" drop constraint "CovidCases_pkey") la restriccion en la base de datos, supongo que hay que hacer algo en el covidcases.js

**Comment by agustin-golmar** [comment]
Resuelto en v0.4.0.
